clean:
	rm ./mrtmp.*

2A:
	go test -run 2A

2A1:
	go test -run InitialElection2A

2A2:
	go test -run ReElection2A


2B1:
	go test -run TestBasicAgree2B

2B:
	go test -run 2B

2B2:
	go test -run TestFailAgree2B

