clean:
	rm ./mrtmp.*

2A:
	go test -run 2A

2A1:
	go test -run InitialElection2A

2A2:
	go test -run ReElection2A


2B1:
	go test -run TestBasicAgree2B

2B:
	go test -run 2B

2B2:
	go test -run TestFailAgree2B

2B3:
	go test -run TestNoAgree2B

2B4:
	go test -run TestConcurrentStarts2B

2B5:
	go test -run TestRejoin2B

2B6:
	go test -run TestBackup2B

2B7:
	go test -run TestCount2B


