clean:
	rm ./mrtmp.*

2A:
	go test -run 2A

2A1:
	go test -run InitialElection2A

2A2:
	go test -run ReElection2A


2B1:
	go test -run TestBasicAgree2B

2B:
	go test -run 2B

2B2:
	go test -run TestFailAgree2B

2B3:
	go test -run TestFailNoAgree2B

2B4:
	go test -run TestConcurrentStarts2B

2B5:
	go test -run TestRejoin2B

2B6:
	go test -run TestBackup2B

2B7:
	go test -run TestCount2B

2C1:
	go test -run TestPersist12C

2C2:
	go test -run TestPersist32C

2C3:
	go test -run TestFigure82C

2C31:
	go test -run TestUnreliableAgree2C

2C4:
	go test -run TestFigure8Unreliable2C

2C5:
	go test -run TestReliableChurn2C

2C6:
	go test -run TestUnreliableChurn2C
